### ISSUE TITLE
Add Module Version Numbers

### ISSUE THREAD

**Issue by awig** [ttinoco/PFNET.py#1]
See [PEP 396 optional standard](https://www.python.org/dev/peps/pep-0396/)

Basically, add support for `pfnet.__version__` 

@ttinoco  If you agree, let's discuss because we'll want to make sure the version number is only maintained in one place (setup.py as it currently is perhaps).  The PEP standard makes some recommendations I can read more about.

**Comment by ttinoco** [comment]
Thanks @awig
right now version is in multiple places:
python: setup.py, docs/conf.py (I feel like I am missing something)
c: docs/conf.py, autoconf.ac, Cmakelists.txt, docs/doxyfile
Would be nice to have in C and Python repos a single file VERSION that has
the version number of everything else gets it from there

**Comment by ttinoco** [comment]
done
