### ISSUE TITLE
add parser that converts grg-pssedata to pfnet network and back

### ISSUE THREAD

**Issue by ttinoco** [ttinoco/PFNET.py#11]
https://github.com/lanl-ansi/grg-pssedata

**Comment by jbarberia** [comment]
There is some methods to indicate if the shunt is fixed or switched. But, how we indicate if the shunt is part of transformer? 
I know the existence of the `shunt.is_part_of_transformer()` method, but how it determines that the shunt is part of transformer. Exist a `shunt.set_as_part_of_transformer()` method?

**Comment by ttinoco** [comment]
Contribution from @jbarberia has been merged into dev.
