### ISSUE TITLE
Windows Build: ImportError: DLL load failed

### ISSUE THREAD

**Issue by jbarberia** [ttinoco/PFNET.py#28]
It could be modified as follows: ```package_data = {'pfnet': ['libpfnet *', '*.dll']}``` to avoid ```ImportError: DLL load failed: The specified module could not be found```  when you use pfnet outside the PFNET.py folder. since pfnet.dll is not copied to the ```Python/Lib/ site-packages/PFNET.egg``` folder.

_Originally posted by @jbarberia in https://github.com/ttinoco/PFNET.py/pull/27#r549553181_

**Comment by ttinoco** [comment]
Issue addressed. Thanks!

**Comment by jbarberia** [comment]
Thanks to you!
