### ISSUE TITLE
test_constr_CFUNC fails on Max OSX

### ISSUE THREAD

**Issue by awig** [ttinoco/PFNET.py#4]
Running the latest dev unittests on my mac osx 10.11

```
======================================================================
FAIL: test_constr_CFUNC (tests.test_constraints.TestConstraints)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ajwigington/projects/Power/PFNET.py/tests/test_constraints.py", line 86, in test_constr_CFUNC
    pf.tests.utils.check_constraint_Jacobian(self, constr, x, np.zeros(0), NUM_TRIALS, TOL, EPS, h, quiet=True)
  File "/Users/ajwigington/projects/Power/PFNET.py/pfnet/tests/utils.py", line 141, in check_constraint_Jacobian
    test.assertLessEqual(error, eps)
AssertionError: 2092.4429701875902 not less than or equal to 5.0

----------------------------------------------------------------------
Ran 164 tests in 418.506s
```

this is the only test that fails

**Comment by awig** [comment]
@ttinoco let me know what information you would need to help debug (case being tested  for example)

**Comment by ttinoco** [comment]
@awig, yes, I can see the test failing on travis on osx. It passes on linux
python 2.7 so it should be ok. The tests are random and some times values
can be very small and hence relative errors can be large. I need to update
the safeguards in the tests. Basically I need to update the test not the
constraint. The test for the "constrained function" are also failing on
python 3 but for incompatibility issues.

**Comment by awig** [comment]
Okay. Do you want me to leave this open or close it?

**Comment by ttinoco** [comment]
Can leave it open,  thanks

**Comment by ttinoco** [comment]
fixed
