### ISSUE TITLE
pip install of mingwpy on anaconda 3 does not work

### ISSUE THREAD

**Issue by ttinoco** [ttinoco/PFNET.py#5]
https://anaconda.org/carlkl/mingwpy

**Comment by jbarberia** [comment]
Somehow I was able to use PFNET with the python3 anaconda distribution through [this](https://github.com/jbarberia/PFNET.py/wiki/How-to-install-on-Windows-and-Python3.X).

**Comment by ttinoco** [comment]
Thanks. I updated the windows build (in dev) to follow https://github.com/romcon/PFNET.py/blob/dev/build_lib.bat and use "microsoft visual 16 2019" compilers.  With this, pfnet.py windows building and testing with Python 3 is working in appveyor.
